package henfredemars;

public enum DataStatus {
	OUT_OF_RANGE_TEMPERATURE,
	OUT_OF_RANGE_HUMIDITY,
	OUT_OF_RANGE_WINDSPEED,
	OUT_OF_RANGE_PRESSURE,
	OUT_OF_RANGE_RAINFALL,
	MISSING_TEMPERATURE,
	MISSING_HUMIDITY,
	MISSING_WINDSPEED,
	MISSING_PRESSURE,
	MISSING_RAINFALL,
	MISSING_STATION,
	MISSING_DATE,
	BAD_STATION,
	ALL_GOOD
}
